# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arctiq Inc.
host: 0.0.0.0
#email: your-email@example.com
address: Arctiq, 41 Britain Street, Suite 302, Toronto, ON, M5A 1R7, Canada
description: > # this means to ignore newlines until "baseurl:"
  Arctiq is a services-led firm providing expertise in the new world of IT transformation.  We help clients build continuous improvement strategies using automation, orchestration, DevOps methodologies, security, and customized workflows. Arctiq helps development teams focus on development efforts and not infrastructure.  Efficiencies are achieved through microservices and container-based solutions, self-service enablement, and repeatable deployment methodologies.  Arctiq’s solutions help reduce risk and simplify tasks through standardized frameworks, workflow automation, and foundational IT practices.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://constitution.arctiq.ca" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ArctiqTeam
github_username:  ArctiqTeam
markdown: kramdown
timezone: UTC
safe: No
#theme: minima
# Tags
tag_dir: tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      robots: noindex

exclude:
  - empty_folder*
  - vendor/
  - bundle/
  - Dockerfile*
  - Gemfile*
  - docker-compose.yml
  - CNAME
  - CONTRIBUTING.md
  - README.md
  - Holacracy-Constitution.md
  - LICENSE.md
  - "Adoption Declaration.md"
  - Discussions.md
  - FAQ.md
  - Appendix-A.md
